### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by talentlessguy** [talentlessguy/tinyhttp#21]
Here's a list of examples to be added:

- [x] Async
- [x] Cookie
- [x] Auth (JWT)
- [x] Basic
- [x] DevServer
- [x] No match handler
- [x] Preact SSR
- [x] TypeScript
- [x] MongoDB
- [x] React SSR (#109)
- [x] GraphQL
- [ ] [Real-world](https://github.com/gothinkster/realworld) app (#147)
- [x] Multi-process
- [x] Serverless lambda (deployed on Vercel)
- [x] HTTP/2
- [x] HTTPS
- [x] Vue SSR
- [x] Markdown blog (with frontmatter extraction) (#141)
- [x] Auth (Session) (#103)
- [x] PostgreSQL (using `pg-promise` or similar) (#104)
- [x] Next.js custom server
- [x] Decorators
- [x] File upload
- [x] [LowDB](https://github.com/typicode/lowdb)
- [x] [Prisma](https://prisma.io) (#95)
- [x] PostgreSQL + TypeORM (#145)
- [x] [FaunaDB](https://fauna.com)
- [x] EJS
- [x] Pug
- [x] Eta
- [x] Svelte SSR (#93)
- [x] Prisma + GraphQL (#116)
- [x] Search "engine" (using Redis or a simple array) (#146)
- [x] Caddy (reverse proxy w/ caddy + working `networkExtensions`) (#158)
- [x] AWS Serverless (#169)
- [x] Firebase functions (#171)
- [x] Hyperapp SSR (#168)
- [x] OpenAPI validation (#186)

- other

**Comment by RocktimSaikia** [comment]
@talentlessguy I don't see `CouchDB` in the list !?

**Comment by RocktimSaikia** [comment]
@talentlessguy ping

**Comment by talentlessguy** [comment]
@RocktimSaikia ohh my bad, I meant RethinkDB

**Comment by RocktimSaikia** [comment]
@talentlessguy lol ok. So we don't need CouchDB examples ?

**Comment by talentlessguy** [comment]
@RocktimSaikia can add CouchDB as well. The more examples we have, the better

**Comment by RocktimSaikia** [comment]
@talentlessguy  is the use of es6 import statements necessary in the examples? Can we not use commonjs `require`?

**Comment by talentlessguy** [comment]
@RocktimSaikia it is necessary

for CJS imports use `import mod from 'mod'`

**Comment by RocktimSaikia** [comment]
@talentlessguy I am currently working on `couchDB` but when testing it `POST` requests I am getting the form data as unfiltered strings not as JSON objects!?!
[ps: I am using `parsec` middleware.]

![Screenshot_2](https://user-images.githubusercontent.com/33410545/91653080-d2d1c180-eaba-11ea-9ace-b6bfdfea72dd.png)

**Comment by talentlessguy** [comment]
@RocktimSaikia use Express `body-parser` then
